### ISSUE TITLE
Ability to specify target path to download to

### ISSUE THREAD

**Issue by vutran** [vutran/zel#15]
// TODO

Add a flag to allow a user to specify a target directory to run `zel`. By default, it should continue to run in the current working directory.

This will make it useful for syncing dotfiles to the user's home directory. (`~/.vimrc`, `~/.zshrc`, etc.)

Optional: Add alias flag `--home` for the user's home directory.

Example:

```bash

# format
# zel --target <targetDir> <repository>

# clone user/repoName to ~/some/path
$ zel --target ~/some/path user/repoName

# equivalent to  `zel --target ~/ vutran/home`
$ zel --home vutran/home
```

**Comment by lukeed** [comment]
Nice 👍 Although the format/order wouldn't matter. With all of these minimist/cli-parsers, a flag's key is assigned the following value string, if any.

```sh
# normal use, read local config
$ zel

# normal use, read remote repo
$ zel vutran/gitignore

# read remote repo, specify target
$ zel vutran/dotfiles --target ~/.config
$ zel vutran/dotfile --home
```

Doesn't change anything 😜 Just typing it out for my own eyes. Nice & consistent
