### ISSUE TITLE
Remove failFast option

### ISSUE THREAD

**Issue by vutran** [vutran/zel#16]
I'm being indecisive but I think we should remove the `failFast` option and just make it terminate early by default. This will simplify the resolver and keep things smaller.

**Comment by lukeed** [comment]
I'd vote that if it were dropped, it should run all by default. The alternative could mean finding out broken repos 1-by-1, which could be annoying.

**Comment by vutran** [comment]
I hear you. I think running all would bump up the priority for authenticated requests since it kind of sucks to be limited at about 60 dependencies (not that I have a real world use case for it right now 😄 )
