### ISSUE TITLE
Auth Token

### ISSUE THREAD

**Issue by lukeed** [vutran/zel#17]
Until we can figure out a secure way to store an auth token (so that it's not stolen/abused), we should add a flag for passing in an auth token.

```sh
$ zel vutran/new --token 7qyL456ro9b766460g79ozj252Z3P370

$ zel --token 7qyL456ro9b766460g79ozj252Z3P370
```

Also useful for the tests yet to be created.

**Comment by vutran** [comment]
Merged in #36
