### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by vutran** [vutran/zel#23]
// TODO

Choice of testing framework is up for discussion.

My own personal preference is to use `jest` + `coveralls` for code cov.

Setup is very easy and includes a very nice API for mocking. `ava` is also another good alternative.

**Comment by lukeed** [comment]
Up to you. I switch between AVA and tape. I use AVA when it helps to have babel-runtime or serup/teardown per test; neither of which we need here.

**Comment by vutran** [comment]
Closed. Using `jest` as choice framework.
