### ISSUE TITLE
Support glob patterns in `files` 

### ISSUE THREAD

**Issue by lukeed** [vutran/zel#5]
For the lazy...

```js
{
  // all dot files
  "files": [".*"],
  // everthing in `src`
  "files": ["src/**"],
  // everything (special case)
  "files": ["*"]
}
```

**Comment by lukeed** [comment]
Actually, I feel like I should be able to `zel` and repository, even if it doesn't have a `.zel` file. This way I can clone any repo without worrying about reinitializing git.

Also adds a lot of reuse & drops the need for creating a zel-specific repo for everything!

```sh
$ zel lukeed/preact-starter
# vs
$ hub clone lukeed/preact-starter && cd preact-starter && rm -rf .git && git init
```

Becomes a tool for instant boilerplate copies. Yeoman-like, but with the option of using anything/everythng.

What do you think?

**Comment by vutran** [comment]
I can definitely see a great benefit of this. We can probably make this work by allowing `zel` to copy all files by default, unless it's explicitly specified in a `.zel` file.

**Comment by vutran** [comment]
We can close this (as of #51)
