### ISSUE TITLE
Resolve and validate all dependencies/files before cloning

### ISSUE THREAD

**Issue by vutran** [vutran/zel#7]
// TODO

We should resolve all dependencies, and validate all files before begin downloading.

**Comment by lukeed** [comment]
Nice. How would you validate files though?

**Comment by vutran** [comment]
Most likely be a GitHub Contents API lookup but will have research more since we'll most likely hit the API rate limit. There is also [this endpoint](https://developer.github.com/v3/git/trees/#get-a-tree) which would allow us to add versioning as well but that could come way later in the future.

**Comment by lukeed** [comment]
I'm thinking about versioning too, but should use tags imo. Bower status.

**Comment by vutran** [comment]
Related: #18

**Comment by vutran** [comment]
Closing as resolver has been added.
